version: "3.7"

services:
  backend:
    image: backend-image
    ports:
      - "8080:8080"
    restart: unless-stopped
  frontend:
    image: frontend-image
    ports:
      - "4200:4200"
    depends_on:
      - backend
    restart: unless-stopped
