-- insert admin account
INSERT INTO users (id, username, password, display_name, role) VALUES ( 1, 'admin', 'admin', 'Admin 1', 0 );

-- insert normal user accounts
INSERT INTO users (id, username, password, display_name, role) VALUES ( 2, 'user1', 'password', 'User 1', 1 );
INSERT INTO users (id, username, password, display_name, role) VALUES ( 3, 'user2', 'password', 'User 2', 1 );

-- insert posts
INSERT INTO posts (id, content, published_on, published_by) VALUES ( 4, 'Donec efficitur, velit sed imperdiet placerat, neque turpis facilisis nibh, sit amet tincidunt tortor ante sit amet nulla. Etiam sagittis ullamcorper scelerisque. Donec fringilla enim sem, ac pharetra sapien vulputate vitae. Proin malesuada magna lacus, eget laoreet orci cursus quis. Sed dictum blandit vestibulum. Vestibulum ante ipsum primis in faucibus.', '2023-06-04 09:40:48.021', 2 );
INSERT INTO posts (id, content, published_on, published_by) VALUES ( 5, 'Donec efficitur, velit sed imperdiet placerat, neque turpis facilisis nibh, sit amet tincidunt tortor ante sit amet nulla. Etiam sagittis ullamcorper scelerisque. Donec fringilla enim sem, ac pharetra sapien vulputate vitae. Proin malesuada magna lacus, eget laoreet orci cursus quis. Sed dictum blandit vestibulum. Vestibulum ante ipsum primis in faucibus.', '2023-06-04 09:42:48.021', 2 );
INSERT INTO posts (id, content, published_on, published_by) VALUES ( 6, 'Donec efficitur, velit sed imperdiet placerat, neque turpis facilisis nibh, sit amet tincidunt tortor ante sit amet nulla. Etiam sagittis ullamcorper scelerisque. Donec fringilla enim sem, ac pharetra sapien vulputate vitae. Proin malesuada magna lacus, eget laoreet orci cursus quis. Sed dictum blandit vestibulum. Vestibulum ante ipsum primis in faucibus.', '2023-06-04 09:43:48.021', 2 );
INSERT INTO posts (id, content, published_on, published_by) VALUES ( 7, 'Donec efficitur, velit sed imperdiet placerat, neque turpis facilisis nibh, sit amet tincidunt tortor ante sit amet nulla. Etiam sagittis ullamcorper scelerisque. Donec fringilla enim sem, ac pharetra sapien vulputate vitae. Proin malesuada magna lacus, eget laoreet orci cursus quis. Sed dictum blandit vestibulum. Vestibulum ante ipsum primis in faucibus.', '2023-06-04 09:34:48.021', 2 );
INSERT INTO posts (id, content, published_on, published_by) VALUES ( 8, 'Donec efficitur, velit sed imperdiet placerat, neque turpis facilisis nibh, sit amet tincidunt tortor ante sit amet nulla. Etiam sagittis ullamcorper scelerisque. Donec fringilla enim sem, ac pharetra sapien vulputate vitae. Proin malesuada magna lacus, eget laoreet orci cursus quis. Sed dictum blandit vestibulum. Vestibulum ante ipsum primis in faucibus.', '2023-06-04 09:45:48.021', 2 );
INSERT INTO posts (id, content, published_on, published_by) VALUES ( 9, 'Donec efficitur, velit sed imperdiet placerat, neque turpis facilisis nibh, sit amet tincidunt tortor ante sit amet nulla. Etiam sagittis ullamcorper scelerisque. Donec fringilla enim sem, ac pharetra sapien vulputate vitae. Proin malesuada magna lacus, eget laoreet orci cursus quis. Sed dictum blandit vestibulum. Vestibulum ante ipsum primis in faucibus.', '2023-06-04 09:36:48.021', 2 );

INSERT INTO posts (id, content, published_on, published_by) VALUES ( 10, 'Donec vitae viverra tellus. Proin ultrices mauris nec mi facilisis congue. Donec libero sapien, pellentesque maximus elit vitae, hendrerit maximus justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus dictum sagittis finibus. Aenean fringilla tortor a turpis laoreet, efficitur efficitur quam sagittis. Maecenas vulputate.', '2023-06-04 09:40:48.021', 1 );
INSERT INTO posts (id, content, published_on, published_by) VALUES ( 11, 'Donec vitae viverra tellus. Proin ultrices mauris nec mi facilisis congue. Donec libero sapien, pellentesque maximus elit vitae, hendrerit maximus justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus dictum sagittis finibus. Aenean fringilla tortor a turpis laoreet, efficitur efficitur quam sagittis. Maecenas vulputate.', '2023-06-04 09:42:48.021', 1 );
INSERT INTO posts (id, content, published_on, published_by) VALUES ( 12, 'Donec vitae viverra tellus. Proin ultrices mauris nec mi facilisis congue. Donec libero sapien, pellentesque maximus elit vitae, hendrerit maximus justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus dictum sagittis finibus. Aenean fringilla tortor a turpis laoreet, efficitur efficitur quam sagittis. Maecenas vulputate.', '2023-06-04 09:43:48.021', 1 );

INSERT INTO posts (id, content, published_on, published_by) VALUES ( 13, 'Maecenas varius ex non arcu ultricies, et suscipit mi volutpat. Nulla neque arcu, interdum eu tellus volutpat, pretium tincidunt nunc. Vestibulum venenatis velit in euismod efficitur. Donec ante nunc, eleifend sed dictum non, dictum et nunc. Proin quis sapien sit amet justo convallis imperdiet. Fusce faucibus dolor ultricies, finibus est.', '2023-06-04 09:34:48.021', 3 );
INSERT INTO posts (id, content, published_on, published_by) VALUES ( 14, 'Maecenas varius ex non arcu ultricies, et suscipit mi volutpat. Nulla neque arcu, interdum eu tellus volutpat, pretium tincidunt nunc. Vestibulum venenatis velit in euismod efficitur. Donec ante nunc, eleifend sed dictum non, dictum et nunc. Proin quis sapien sit amet justo convallis imperdiet. Fusce faucibus dolor ultricies, finibus est.', '2023-06-04 09:45:48.021', 3 );
INSERT INTO posts (id, content, published_on, published_by) VALUES ( 15, 'Maecenas varius ex non arcu ultricies, et suscipit mi volutpat. Nulla neque arcu, interdum eu tellus volutpat, pretium tincidunt nunc. Vestibulum venenatis velit in euismod efficitur. Donec ante nunc, eleifend sed dictum non, dictum et nunc. Proin quis sapien sit amet justo convallis imperdiet. Fusce faucibus dolor ultricies, finibus est.', '2023-06-04 09:36:48.021', 3 );

-- restart id_sequence
alter sequence id_sequence restart with 16;
